(defun fizzbuzz (n)
    (setq i 1)
    (while (<= i n)
        (if (== (% i 15) 0)
            (print "fizzbuzz")
            (if (== (% i 3) 0)
                (print "fizz")
                (if (== (% i 5) 0)
                    (print "buzz")
                    (print i)
                )
            )
        )
        (+= i 1)
    )
)
(fizzbuzz 30)